### ISSUE TITLE
Add one shot kubeconfig generation command

### ISSUE THREAD

**Issue by mattmoyer** [heptiolabs/kubernetes-aws-authenticator#5]
Right now you have to bring up a cluster, then install the DaemonSet, then go back and restart the API server with the new CLI flag to enable the webhook.

If you're trying to provision a cluster with a script, it would be nice to be able to generate the kubeconfig (and associated certificate and key) ahead of time. This would let you do it prior to initially bringing up the control plane.

Maybe `kubernetes-aws-authenticator pregenerate`?

**Comment by mumoshu** [comment]
@mattmoyer Hi, thanks for sharing this project 👍 
While learning kubernetes-aws-authenticator I've created #10 for this.
Would you mind reviewing it if it could help your work? 😉
